/*
 * Copyright © 2017-2018 William Peckham
 *
 * This file is part of LibNoise4Java.
 * 
 * LibNoise4Java is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * LibNoise4Java is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with LibNoise4Java.  If not, see <http://www.gnu.org/licenses/>. 
 */

package com.matrixpeckham.libnoise.util.exceptions;

import java.util.logging.Logger;
import static java.util.logging.Logger.getLogger;

/**
 * Base class for exceptions generated by LibNoise4Java
 *
 * @author William Matrix Peckham
 */
public class NoiseException extends RuntimeException {

    private static final Logger LOG = getLogger(NoiseException.class.getName());

    private static final long serialVersionUID = 1L;

    /**
     * Default constructor.
     */
    public NoiseException() {
    }

    /**
     * Constructor with message.
     *
     * @param message
     */
    public NoiseException(String message) {
        super(message);
    }

    /**
     * Constructor with message and cause.
     *
     * @param message
     * @param cause
     */
    public NoiseException(String message, Throwable cause) {
        super(message, cause);
    }

    /**
     * Constructor with cause.
     *
     * @param cause
     */
    public NoiseException(Throwable cause) {
        super(cause);
    }

    /**
     * Constructor with message, cause and boolean flags.
     *
     * @param message
     * @param cause
     * @param enableSuppression
     * @param writableStackTrace
     */
    public NoiseException(String message, Throwable cause,
            boolean enableSuppression, boolean writableStackTrace) {
        super(message, cause, enableSuppression, writableStackTrace);
    }

}
