/*
 * DEFAULT LICENSE
 * Do not make illegal copies
 * This software is provided as is, without any warranty at all
 * Not responsible for any damage to anything that may occur
 * Copyright © 2012 William Peckham
 */
package com.matrixpeckham.libnoise.util.exceptions;

import java.util.logging.Logger;
import static java.util.logging.Logger.getLogger;

/**
 * Base class for exceptions generated by LibNoise4Java
 *
 * @author William Matrix Peckham
 */
public class NoiseException extends RuntimeException {

    private static final Logger LOG = getLogger(NoiseException.class.getName());

    private static final long serialVersionUID = 1L;

    /**
     * Default constructor.
     */
    public NoiseException() {
    }

    /**
     * Constructor with message.
     *
     * @param message
     */
    public NoiseException(String message) {
        super(message);
    }

    /**
     * Constructor with message and cause.
     *
     * @param message
     * @param cause
     */
    public NoiseException(String message, Throwable cause) {
        super(message, cause);
    }

    /**
     * Constructor with cause.
     *
     * @param cause
     */
    public NoiseException(Throwable cause) {
        super(cause);
    }

    /**
     * Constructor with message, cause and boolean flags.
     *
     * @param message
     * @param cause
     * @param enableSuppression
     * @param writableStackTrace
     */
    public NoiseException(String message, Throwable cause,
            boolean enableSuppression, boolean writableStackTrace) {
        super(message, cause, enableSuppression, writableStackTrace);
    }

}
