/*
 * DEFAULT LICENSE
 * Do not make illegal copies
 * This software is provided as is, without any warranty at all
 * Not responsible for any damage to anything that may occur
 * Copyright © 2012 William Peckham
 */
package com.matrixpeckham.libnoise.module;

/**
 * Noise module that caches the last output value generated by a source module.
 *
 * If an application passes an input value to the GetValue() method that differs
 * from the previously passed-in input value, this noise module instructs the
 * source module to calculate the output value. This value, as well as the ( @a
 * x, @a y, @a z ) coordinates of the input value, are stored (cached) in this
 * noise module.
 *
 * If the application passes an input value to the GetValue() method that is
 * equal to the previously passed-in input value, this noise module returns the
 * cached output value without having the source module recalculate the output
 * value.
 *
 * If an application passes a new source module to the SetSourceModule() method,
 * the cache is invalidated.
 *
 * Caching a noise module is useful if it is used as a source module for
 * multiple noise modules. If a source module is not cached, the source module
 * will redundantly calculate the same output value once for each noise module
 * in which it is included.
 *
 * This noise module requires one source module.
 *
 * @author William Matrix Peckham
 */
public class Cache extends Module {

    /**
     * The cached output value at the cached input value.
     */
    protected double cachedValue;

    /**
     * determine if the output value is stored in this module
     */
    protected boolean isCached;

    /**
     * x coordinate of the input value
     */
    protected double xCache;

    /**
     * y coordinate of the input value
     */
    protected double yCache;

    /**
     * z coordinate of the input value
     */
    protected double zCache;

    public Cache() {
        isCached = false;
    }

    @Override
    public void setSourceModule(int index, Module source) {
        super.setSourceModule(index, source); //To change body of generated methods, choose Tools | Templates.
        isCached = false;
    }

    @Override
    public int getSourceModuleCount() {
        return 1;
    }

    @Override
    public double getValue(double x, double y, double z) {
        if (!(isCached && xCache == x && yCache == y && zCache == z)) {
            cachedValue = sourceModule[0].getValue(x, y, z);
            xCache = x;
            yCache = y;
            zCache = z;
        }
        isCached = true;
        return cachedValue;
    }

}
