/*
 * DEFAULT LICENSE
 * Do not make illegal copies
 * This software is provided as is, without any warranty at all
 * Not responsible for any damage to anything that may occur
 * Copyright © 2012 William Peckham
 */
package com.matrixpeckham.libnoise.model;

import com.matrixpeckham.libnoise.module.Module;


public class Plane {

    private Module module;

    public Module getModule() {
        return module;
    }

    /**
     * Returns the output value from the noise module given the ( @a x, @a z )
     * coordinates of the specified input value located on the surface of the
     * plane.
     *
     * @param x The @a x coordinate of the input value.
     * @param z The @a z coordinate of the input value.
     *
     * @returns The output value from the noise module.
     *
     * @pre A noise module was passed to the SetModule() method.
     *
     * This output value is generated by the noise module passed to the
     * SetModule() method.
     */
    public double getValue(double x, double z) {
        return module.getValue(x, 0, z);
    }

    public void setModule(Module module) {
        this.module = module;
    }

}
