/*
 * DEFAULT LICENSE
 * Do not make illegal copies
 * This software is provided as is, without any warranty at all
 * Not responsible for any damage to anything that may occur
 * Copyright © 2012 William Peckham
 */
package com.matrixpeckham.libnoise.model;

import com.matrixpeckham.libnoise.module.Module;
import static com.matrixpeckham.libnoise.util.Globals.latLonToXYZ;
import com.matrixpeckham.libnoise.util.Vec3;


public class Sphere {

    private Module module;

    public Sphere() {
    }

    public Sphere(Module m) {
        module = m;
    }

    public Module getModule() {
        return module;
    }

    /**
     * Returns the output value from the noise module given the (latitude,
     * longitude) coordinates of the specified input value located on the
     * surface of the sphere.
     *
     * @param lat The latitude of the input value, in degrees.
     * @param lon The longitude of the input value, in degrees.
     *
     * @returns The output value from the noise module.
     *
     * @pre A noise module was passed to the SetModule() method.
     *
     * This output value is generated by the noise module passed to the
     * SetModule() method.
     *
     * Use a negative latitude if the input value is located on the southern
     * hemisphere.
     *
     * Use a negative longitude if the input value is located on the western
     * hemisphere.
     */
    public double getValue(double lat, double lon) {
        Vec3 v = latLonToXYZ(lat, lon);
        return module.getValue(v.x, v.y, v.z);
    }

    public void setModule(Module module) {
        this.module = module;
    }
}
